language: node_js
node_js:
- '6.2'
cache:
  directories:
  - node_modules
  - "$HOME/.npm"
  - "$HOME/.gem"
before_install:
- npm install -g gulp
script:
- gulp test
before_deploy:
- gulp
deploy:
  provider: npm
  email: me@brianneisler.com
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: djCpO1aeb4dfPIrjThQY2uvyC86R5UCpAFnmSWivbVRnaRCopCSdTKXYqwxnfTWkOMDIFn54VZYZMLixYyEO44J1nx6qjxx5fSJjtzqH/KyRn14FhyjhuE9LVzffwaGzaLSG/nuazRth0zm9FBSlBTCBu9XHNAu9cL/Bf9XH4b+tM/mRmoaXX0OXm5uQCCOZ1wVM/pRGvj0noYREqgOCjOefHEoO+X/gOnLECncVYHPJmUrqZBwrTvu8YdNtQErfoSBE+BMw5F91kyihiugzA/DisRMBkiIz8cfsW4ETuMA4x6I4Tb7X+v5276KsrM8Xd53d6VA0s3ynqFRQI3sMX5UdmfTQ63F/Drm5kBbAQlkdDsh+mXXhOqo13TMCSMvIeI7rUKLOOG1huvhEMDb4vx7ZaChbjT2xkHBxwdEbscUiQ9SJxqnMLGERim7sM8jOLK6BgoMg2knjwwsUNTJ2O1KArk89j2IghnBV1XyusyTyMkYkPDMTO8jgtcxfi2tSfjaDe+hs1rJQHVFHEmtZRvXwC3nyW/teEuj4x5XBNc3R1N7Q2gZDvomwRJx5fqiKoKy/XduOXP0iuvVzG/dqoK6CrTER2ei+d8VXloIjtHMZASqCVlBCfjTN1/qT1Gb7mSUl+5LeAwxW8GVREcd3TiW/t+51ImC9aKzzS6d719A=
